### ISSUE TITLE
ImportError when importing KmeansNANI

### ISSUE THREAD

**Issue by nbruciaferri** [mqcomplab/MDANCE#74]
Hi, I'm trying to use NANI to cluster some structures and after updating to the latest version (`v0.3.7`) when I try to run:

`from mdance.cluster.nani import KmeansNANI`

The following error is raised:

```
      5 import MDAnalysis as mda
      6 import numpy as np
----> 7 from shapeGMMTorch import torch_align
      8 import torch
     10 import mdance.tools.esim as esim

ImportError: cannot import name 'torch_align' from 'shapeGMMTorch'
```

**Comment by nbruciaferri** [comment]
It seems it doesn't work with the latest version of `shapeGMMTorch` (`v2.0.0`) but it works with `v1.7.1`
